/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemaRouteImport } from './routes/tema'
import { Route as ObjetivosRouteImport } from './routes/objetivos'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as IndexRouteImport } from './routes/index'

const TemaRoute = TemaRouteImport.update({
  id: '/tema',
  path: '/tema',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivosRoute = ObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mercado': typeof MercadoRoute
  '/objetivos': typeof ObjetivosRoute
  '/tema': typeof TemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mercado': typeof MercadoRoute
  '/objetivos': typeof ObjetivosRoute
  '/tema': typeof TemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mercado': typeof MercadoRoute
  '/objetivos': typeof ObjetivosRoute
  '/tema': typeof TemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mercado' | '/objetivos' | '/tema'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mercado' | '/objetivos' | '/tema'
  id: '__root__' | '/' | '/mercado' | '/objetivos' | '/tema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MercadoRoute: typeof MercadoRoute
  ObjetivosRoute: typeof ObjetivosRoute
  TemaRoute: typeof TemaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tema': {
      id: '/tema'
      path: '/tema'
      fullPath: '/tema'
      preLoaderRoute: typeof TemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivos': {
      id: '/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof ObjetivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MercadoRoute: MercadoRoute,
  ObjetivosRoute: ObjetivosRoute,
  TemaRoute: TemaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
